# Generated by Django 6.1.1 on 2026-09-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(blank=True, default='', max_length=255)),
                ('station_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('police_district', models.CharField(db_index=True, max_length=100)),
                ('revenue_district', models.CharField(db_index=True, max_length=100)),
                ('station_type', models.CharField(default='General', max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('identification_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Stations',
                'ordering': ['police_district', 'station_name'],
            },
        ),
        migrations.CreateModel(
            name='PoliceStationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='core.policestation')),
            ],
        ),
    ]
