# Generated by Django 6.1.1 on 2026-09-11 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('complaint_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Assigned', 'Assigned'), ('Under Investigation', 'Under Investigation'), ('Action Taken', 'Action Taken'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, default='Submitted', max_length=50)),
                ('evidence_info', models.TextField(blank=True, default='')),
                ('investigation_notes', models.TextField(blank=True, default='')),
                ('assigned_officer', models.CharField(blank=True, default='Pending Assignment', max_length=150)),
                ('complainant_name', models.CharField(blank=True, default='Citizen', max_length=150)),
                ('complainant_contact', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.policestation')),
            ],
            options={
                'verbose_name': 'Citizen Complaint',
                'verbose_name_plural': 'Citizen Complaints',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('crime_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Assigned', 'Assigned'), ('Under Investigation', 'Under Investigation'), ('Action Taken', 'Action Taken'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, default='Submitted', max_length=50)),
                ('evidence_info', models.TextField(blank=True, default='')),
                ('investigation_notes', models.TextField(blank=True, default='')),
                ('assigned_officer', models.CharField(blank=True, default='Pending Assignment', max_length=150)),
                ('complainant_name', models.CharField(blank=True, default='Anonymous', max_length=150)),
                ('complainant_contact', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='core.policestation')),
            ],
            options={
                'verbose_name': 'Crime Report',
                'verbose_name_plural': 'Crime Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Assigned', 'Assigned'), ('Under Investigation', 'Under Investigation'), ('Action Taken', 'Action Taken'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('updated_by', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.complaint')),
                ('crime_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.crimereport')),
            ],
            options={
                'verbose_name': 'Case Status History',
                'verbose_name_plural': 'Case Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
