# Generated by Django 5.2.17 on 2026-09-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_crimereport_casestatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence_files/'),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence_files/'),
        ),
    ]
