# Generated by Django 5.2.17 on 2026-09-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_evidence_file_crimereport_evidence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_evidence/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
