# Generated by Django 6.1.1 on 2026-09-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_complaint_audio_file_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_severity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='ai_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='ai_severity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
