# Generated by Django 5.2.17 on 2026-10-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_complaint_user_crimereport_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.complaint')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.policestation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
